function varargout = readMWLdaq_LV(varargin)
%UNTITLED Reads data files from MWLdaq_LV
%   readMWLdaq_LV version 0.2
%
%   reads data files generated by MWLdaq_LV, up to two inputs can be
%   supplied by the user, depending on the user input up to three outputs
%   will be generated
%  
%   [header,spectra,rawdata]=readMWLdaq_LV(fname,strflag)
%
%   fname   ... optional, is the full path and filename to the data storage
%               e.g. C:\path\to\my\file\mwl.dat
%   strflag ... optional, defines which data should be loaded, one of the
%               following: 'all','spectra','raw'
%
%   header  ... header of the data structure, to be implemented in the not
%               to distant future
%   spectra ... structure containing the spectra
% 
%   rawdata ... NxM cell array containing the raw time series in EU
%               N is the channel number
%               M is the repeat number
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Stefan Jacob; sjacob(at)kth.se 20181127
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% check inputs %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
l=length(varargin);
if l<2
 strflag='all';   %'spectra' 'raw'
else
 if ismember(varargin{2},{'all','rawdata','spectra'})
  strflag=varargin{2};
 else
  strflag='all';
 end
end
if l<1
 [file,path]=uigetfile('*.dat','Select a data file from MWLdaq_LV');
 fname=[path,file];
else
 if isempty(varargin{1})
  [file,path]=uigetfile('*.dat','Select a data file from MWLdaq_LV');
  fname=[path,file];
 else
  fname=varargin{1};
 end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% read in header %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fid=fopen(fname);        % open file
lstr=fgetl(fid);         % read first line
while(~strcmp(lstr,'<Cluster>'))
 lstr=fgetl(fid);
end
ll=1;
MWLdaq.conf{1}=fgetl(fid);
while (~strcmp(MWLdaq.conf{ll},'EndOfConfiguration_HubbaBubba'))
 ll=ll+1;
 MWLdaq.conf{ll}=fgetl(fid);
end
ll=1;
MWLdaq.header{ll}=fgetl(fid);
while (~strcmp(MWLdaq.header{ll},'EndOfHeader_HubbaBubba'))
 ll=ll+1;
 MWLdaq.header{ll}=fgetl(fid);
end
varargout{1}=MWLdaq;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% read in raw data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if strcmp(strflag,'all') || strcmp(strflag,'rawdata')
 frewind(fid);
 while(~strcmp(lstr,'StartRawData') && ~feof(fid))
  lstr=fgetl(fid);
 end
 if ~feof(fid)
 lstr=fgetl(fid);
 while (~strcmp(lstr,'EndRawData'))
  strpos=strfind(lstr,'Repeat');
  chname=str2double(lstr(9:strpos-2))+1;
  strpos2=strfind(lstr,'Date');
  norep=str2double(lstr((strpos+7):strpos2-2))+1;
  strpos=strfind(lstr,'NoPoints');
  nopts=str2double(lstr(strpos+9:end));
  a=fread(fid,2*(nopts)+1,'double');
  a(1)=[];
  raw_data{chname,norep}=[a(1:nopts), a((nopts+1):end)];
  lstr=fgetl(fid);
  lstr=fgetl(fid);
 end
 varargout{2}=raw_data;
 end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% read in spectra %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if strcmp(strflag,'all') || strcmp(strflag,'spectra')
 frewind(fid);
 while(~strcmp(lstr,'StartSpectraData') && ~feof(fid))
  lstr=fgetl(fid);
 end
 if ~feof(fid)
 lstr=fgetl(fid);
 ll=0;
 while (~strcmp(lstr,'EndSpectraData'))
  ll=ll+1;
  strpos1=strfind(lstr,'Display');
  chname=lstr(9:strpos1-2);
  strpos2=strfind(lstr,'NoPoints');
  nopts=str2double(lstr(strpos2+9:end));
  chlabel=lstr(strpos1+8:strpos2-2);
  a=fread(fid,2*(nopts)+1,'double');
  a(1)=[];
  if ~isempty(findstr(chname,'1/3OCT'))
   chname(2)='_';
  end
  eval(['spectra.sig_',num2str(ll),'_',chname,'=[a(1:nopts), a((nopts+1):end)];']);
  eval(['spectra.label_',num2str(ll),'_',chname,'=chlabel;'])
  lstr=fgetl(fid);
  lstr=fgetl(fid);
 end
 varargout{3}=spectra;
 end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% clean up %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fclose(fid);             % close file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end

